### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by ruifcardoso** [tarek360/Material-Animation-Samples#1]
Hi, how do I use this on my project? 

I followed this tutorial but didn't work: https://github.com/MagicMicky/FreemiumLibrary/wiki/Import-the-library-in-Android-Studio

I get this error:
Error:Configuration with name 'default' not found.

**Comment by tarek360** [comment]
hi,
if you want to use my Material-Animation-Samples you clone it but if you talk about https://github.com/MagicMicky/FreemiumLibrary you can make an issue by this link https://github.com/MagicMicky/FreemiumLibrary/issues/new

thanks.

**Comment by ruifcardoso** [comment]
I was saying that since you didnt made a tutorial on how to install, I used that one but I dont want to use the FreemiumLibrary. I wanted to use Material-Animation-Samples so I could add the lollipop transition effects to my app, but I cant add it as a module to use them

**Comment by tarek360** [comment]
Thank you for using Material-Animation-Samples but Material-Animation-Samples is not a library, it is a sample of free code you can implement it in your android project without import any thing.

thank you.
